### ISSUE TITLE
Player will be able to move character on screen through keyboard or controller

### ISSUE THREAD

**Issue by jschwarzwalder** [jschwarzwalder/CodeDay2022#4]
Possible Inspiration: 

- [Top Down Movement ](youtube.com/watch?v=whzomFgjT50)

Questions:

- How will the player interact in-game (Keyboard, Controller, Both?)
- Will Player movement be Pause during Menu or just enemies?

**Comment by Juke-Duke** [comment]
Done.

**Comment by jschwarzwalder** [comment]
This was closed with Animation Movement. 

Creating new Issue for Movement with Collider
